Name = input("Enter Your Name : ")
Address = input("Enter Your Address : ")
Gmail = input("Enter Your Gmail : ")
MobileNumber = input("Enter Your MobileNumber : ")
print("NAME : ",Name)
print("ADDRESS : ", Address)
print("GMAIL : ", Gmail)
print("MOBILE NUMBER : ",MobileNumber)
